### ISSUE TITLE
macOS 11 - nil can't be coerced into Float 

### ISSUE THREAD

**Issue by EionRobb** [sirupsen/initcwnd#1]
Trying to run the script on OSX 11.3, but it errors out with "nil can't be coerced into Float"

```
$ sudo ruby initcwnd.rb https://github.com/sirupsen/initcwnd en0
p50:    46.446ms
avg:    46.39452631578948ms
var:    9.548603878116406e-05ms
stddev: 0.30900815326001363ms
tcpdump: listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  161k    0  161k    0     0   197k      0 --:--:-- --:--:-- --:--:--  197k
215 packets captured
2328 packets received by filter
0 packets dropped by kernel
CLIENT: [0ms/0ms] SYN 78 bytes:

SERVER: [45ms/45ms] SYN+ACK 74 bytes:

CLIENT: [45ms/0ms] ACK 66 bytes:

CLIENT: [628ms/582ms] ACK 583 bytes:

SERVER: [567ms/-61ms] ACK 1490 bytes: TLS KEY EXCH

CLIENT: [567ms/0ms] ACK 66 bytes:

SERVER: [567ms/0ms] ACK 1366 bytes:

CLIENT: [577ms/10ms] ACK 66 bytes:

CLIENT: [590ms/13ms] ACK 130 bytes: TLS SERVER DONE

DONE TLS HANDSHAKE
Traceback (most recent call last):
        3: from initcwnd.rb:101:in `<main>'
        2: from initcwnd.rb:101:in `each'
        1: from initcwnd.rb:208:in `block in <main>'
initcwnd.rb:208:in `-': nil can't be coerced into Float (TypeError)

$ sudo ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]

$ sudo uname -a
Darwin MacMini3.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

```

**Comment by sirupsen** [comment]
Does this happen when you re-run it a few times?

**Comment by EionRobb** [comment]
Just re-ran it 10 times in a row and none of them succeeded, still the same "nil cant be coerced into Float" error.

Just in case it helps, the last run output was

```
$ sudo ruby initcwnd.rb https://github.com/sirupsen/initcwnd en0
p50:    45.971ms
avg:    46.018210526315784ms
var:    9.189837673130228e-05ms
stddev: 0.30314745047798486ms
tcpdump: listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k    0  160k    0     0   541k      0 --:--:-- --:--:-- --:--:--  539k
214 packets captured
313 packets received by filter
0 packets dropped by kernel
CLIENT: [0ms/0ms] SYN 78 bytes:

SERVER: [448ms/448ms] SYN+ACK 74 bytes:

CLIENT: [448ms/0ms] ACK 66 bytes:

CLIENT: [529ms/80ms] ACK 583 bytes:

SERVER: [-157ms/-685ms] ACK 1490 bytes: TLS KEY EXCH

CLIENT: [-156ms/0ms] ACK 66 bytes:

SERVER: [-156ms/0ms] ACK 1366 bytes:

CLIENT: [-155ms/1ms] ACK 66 bytes:

CLIENT: [-154ms/1ms] ACK 130 bytes: TLS SERVER DONE

DONE TLS HANDSHAKE
Traceback (most recent call last):
        3: from initcwnd.rb:101:in `<main>'
        2: from initcwnd.rb:101:in `each'
        1: from initcwnd.rb:208:in `block in <main>'
initcwnd.rb:208:in `-': nil can't be coerced into Float (TypeError)

```

**Comment by sirupsen** [comment]
Weird, comment out those delta calculations lines -- I've seen this before on MacOS, but not repeatedly. The problem is that it's somehow not picking up the beginning of your TLS exchange. The negative timestamps also seem suspicious. Might you have a tab with Github open with e.g. a live socket with live chatter or something? That could cause the confusion.

Obviously the script needs to be more robust, heh, had to run a bit at the end of the post to get it out of the door :)

**Comment by EionRobb** [comment]
Thanks for that suggestion.  Commenting out line 208 got the script running. 👍  The negative timestamps just happened to be on the 10th run, I hadn't noticed until I added the log :)  Previous runs had them all positive.  Yes, there could possibly be a browser window open on that machine to github, but I'm just ssh'ing into.

But yay, it runs now.  I'm not quite sure if the data is correct though, since the first window seems suspiciously small and doesn't line up with your tests in the Readme 

Just for posterity, the output from the log is
```
$ sudo ruby initcwnd.rb https://github.com/sirupsen/initcwnd en0
Password:
p50:    46.222ms
avg:    46.23410526315789ms
var:    8.437009418282531e-05ms
stddev: 0.2904653063324867ms
tcpdump: listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  160k    0  160k    0     0   232k      0 --:--:-- --:--:-- --:--:--  232k
219 packets captured
2458 packets received by filter
0 packets dropped by kernel
CLIENT: [0ms/0ms] SYN 78 bytes:

SERVER: [45ms/45ms] SYN+ACK 74 bytes:

CLIENT: [45ms/0ms] ACK 66 bytes:

CLIENT: [54ms/9ms] ACK 583 bytes:

SERVER: [99ms/46ms] ACK 1490 bytes: TLS KEY EXCH

CLIENT: [100ms/0ms] ACK 66 bytes:

SERVER: [100ms/0ms] ACK 1367 bytes:

CLIENT: [101ms/1ms] ACK 66 bytes:

CLIENT: [101ms/0ms] ACK 130 bytes: TLS SERVER DONE

DONE TLS HANDSHAKE
CLIENT: [102ms/1ms] ACK 289 bytes: TLS DATA

WINDOW 1
DONE TLS HANDSHAKE
SERVER: [146ms/44ms] ACK 145 bytes: TLS DATA

WINDOW 1
DONE TLS HANDSHAKE
SERVER: [146ms/0ms] ACK 145 bytes: TLS DATA

CLIENT: [146ms/0ms] ACK 66 bytes:

SERVER: [189ms/43ms] ACK 66 bytes:

SUSPICIOUSLY LARGE
WINDOW 2
DONE TLS HANDSHAKE
SERVER: [541ms/353ms] ACK 1458 bytes: TLS DATA

CLIENT: [542ms/0ms] ACK 66 bytes:

WINDOW 2
DONE TLS HANDSHAKE
SERVER: [542ms/0ms] ACK 1368 bytes: TLS DATA

WINDOW 2
DONE TLS HANDSHAKE
SERVER: [542ms/0ms] ACK 1458 bytes: TLS DATA

WINDOW 2
DONE TLS HANDSHAKE
SERVER: [542ms/0ms] ACK 1490 bytes: TLS DATA

WINDOW 2
SERVER: [542ms/0ms] ACK 1426 bytes:

WINDOW 2
DONE TLS HANDSHAKE
SERVER: [542ms/0ms] ACK 1490 bytes: TLS DATA

WINDOW 2
SERVER: [542ms/0ms] ACK 1490 bytes:

WINDOW 2
SERVER: [543ms/0ms] ACK 1490 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

CLIENT: [543ms/0ms] ACK 66 bytes:

WINDOW 2
SERVER: [543ms/0ms] ACK 1490 bytes:

WINDOW 2
SERVER: [543ms/0ms] ACK 1490 bytes:

CLIENT: [544ms/1ms] ACK 66 bytes:

CLIENT: [544ms/0ms] ACK 66 bytes:

SUSPICIOUSLY LARGE
WINDOW 3
SERVER: [587ms/43ms] ACK 1490 bytes:

CLIENT: [587ms/0ms] ACK 66 bytes:

WINDOW 3
SERVER: [587ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [587ms/1ms] ACK 1490 bytes:

WINDOW 3
SERVER: [587ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

CLIENT: [588ms/0ms] ACK 66 bytes:

CLIENT: [588ms/0ms] ACK 66 bytes:

CLIENT: [588ms/0ms] ACK 66 bytes:

CLIENT: [588ms/0ms] ACK 66 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [588ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

CLIENT: [589ms/0ms] ACK 66 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

WINDOW 3
SERVER: [589ms/0ms] ACK 1490 bytes:

CLIENT: [590ms/0ms] ACK 66 bytes:

CLIENT: [590ms/0ms] ACK 66 bytes:

CLIENT: [590ms/0ms] ACK 66 bytes:

CLIENT: [590ms/0ms] ACK 66 bytes:

SUSPICIOUSLY LARGE
WINDOW 4
SERVER: [632ms/42ms] ACK 1490 bytes:

WINDOW 4
SERVER: [632ms/0ms] ACK 1490 bytes:

CLIENT: [632ms/0ms] ACK 66 bytes:

WINDOW 4
SERVER: [632ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [632ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/1ms] ACK 1490 bytes:

CLIENT: [633ms/0ms] ACK 66 bytes:

CLIENT: [633ms/0ms] ACK 66 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [633ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

CLIENT: [634ms/0ms] ACK 66 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [634ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

CLIENT: [635ms/0ms] ACK 66 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [635ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

CLIENT: [636ms/0ms] ACK 66 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [636ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [637ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [637ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [637ms/0ms] ACK 1490 bytes:

WINDOW 4
SERVER: [637ms/0ms] ACK 1490 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

CLIENT: [637ms/0ms] ACK 66 bytes:

SUSPICIOUSLY LARGE
WINDOW 5
SERVER: [677ms/39ms] ACK 1490 bytes:

CLIENT: [677ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [677ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [677ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [677ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/1ms] ACK 1490 bytes:

CLIENT: [678ms/0ms] ACK 66 bytes:

CLIENT: [678ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [678ms/0ms] ACK 1490 bytes:

CLIENT: [679ms/0ms] ACK 66 bytes:

CLIENT: [679ms/0ms] ACK 66 bytes:

CLIENT: [679ms/0ms] ACK 66 bytes:

CLIENT: [679ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [679ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

CLIENT: [680ms/0ms] ACK 66 bytes:

CLIENT: [680ms/0ms] ACK 66 bytes:

CLIENT: [680ms/0ms] ACK 66 bytes:

CLIENT: [680ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [680ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

CLIENT: [681ms/0ms] ACK 66 bytes:

CLIENT: [681ms/0ms] ACK 66 bytes:

CLIENT: [681ms/0ms] ACK 66 bytes:

CLIENT: [681ms/0ms] ACK 66 bytes:

CLIENT: [681ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [681ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

CLIENT: [682ms/0ms] ACK 66 bytes:

CLIENT: [682ms/0ms] ACK 66 bytes:

CLIENT: [682ms/0ms] ACK 66 bytes:

CLIENT: [682ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [682ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 1490 bytes:

CLIENT: [683ms/0ms] ACK 66 bytes:

CLIENT: [683ms/0ms] ACK 66 bytes:

CLIENT: [683ms/0ms] ACK 66 bytes:

CLIENT: [683ms/0ms] ACK 66 bytes:

CLIENT: [683ms/0ms] ACK 66 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 1490 bytes:

WINDOW 5
SERVER: [683ms/0ms] ACK 466 bytes:

CLIENT: [684ms/1ms] ACK 66 bytes:

DONE TLS HANDSHAKE
CLIENT: [684ms/0ms] ACK 90 bytes: TLS DATA

CLIENT: [685ms/1ms] FIN+ACK 66 bytes: BYE BYE

SERVER: [729ms/44ms] ACK 66 bytes:

WINDOW 6
DONE TLS HANDSHAKE
SERVER: [729ms/0ms] ACK 90 bytes: TLS DATA

SERVER: [729ms/0ms] FIN+ACK 66 bytes: BYE BYE

CLIENT: [730ms/1ms]  54 bytes:

TCP CONGESTION WINDOW ANALYSIS FOR https://github.com/sirupsen/initcwnd
RTT p50:    46.2 ms
RTT avg:    46.2 ms
RTT var:    0.0 ms
RTT stddev: 0.3 ms

TOTAL UNENCRYPTED, UNCOMPRESSED SIZE (HTML): 164107 bytes
TOTAL NETWORK SIZE (COMPRESSED & ENCRYPTED): 177906 bytes
SERVER PROCESSING TIME: 353 ms
TTFB: 146 ms
TOTAL PACKETS: 122
TOTAL TIME: 729 ms

DATA TIME: 584 ms
DATA ROUNDTRIPS: 6

DATA WINDOWS (NOT TLS):
        WINDOW 1: 2 @ 290 bytes (0.16% of total)
        WINDOW 2: 10 @ 14650 bytes (8.23% of total)
        WINDOW 3: 20 @ 29800 bytes (16.75% of total)
        WINDOW 4: 40 @ 59600 bytes (33.5% of total)
        WINDOW 5: 50 @ 73476 bytes (41.3% of total)
        WINDOW 6: 1 @ 90 bytes (0.05% of total)


Written windows to initcwnd.csv
Written plot to initcwnd.png
Written stats to initcwnds.csv
```

**Comment by EionRobb** [comment]
After killing safari and re-running, it's still got a window 1 size of 2 (with the commented-out line) and still has the 'nill cant be coerced error' when uncommenting

**Comment by EionRobb** [comment]
Thanks for your help :)
